import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedMenu {
  final List<MenuModel> results;

  AutogeneratedMenu({this.results});

  factory AutogeneratedMenu.fromJson(Map<String, dynamic> json) {
    List<MenuModel> temp;
    if (json['results'] != null) {
      temp = <MenuModel>[];
      json['results'].forEach((v) {
        temp.add(MenuModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedMenu(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class MenuModel extends Equatable {
  int id;
  String name;
  String description;
  String photoUrl;
  int dailyStock;

  MenuModel(this.id, this.name, this.description, this.photoUrl, this.dailyStock);

  @override
  List<Object> get props => [id, name, description, photoUrl, dailyStock];

  factory MenuModel.fromJson(Map<String, dynamic> json) {
    return MenuModel(json['id'] as int, 
    json['name'] as String,
    json['description'] as String,
    json['photoUrl'] as String,
    json['dailyStock'] as int,
    );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['description'] = description;
    data['photoUrl'] = photoUrl;
    data['dailyStock'] = dailyStock;
    return data;
  }
}
