import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedOrder {
  final List<OrderModel> results;

  AutogeneratedOrder({this.results});

  factory AutogeneratedOrder.fromJson(Map<String, dynamic> json) {
    List<OrderModel> temp;
    if (json['results'] != null) {
      temp = <OrderModel>[];
      json['results'].forEach((v) {
        temp.add(OrderModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedOrder(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }

}

class OrderModel extends Equatable {
  String orderId;
  String userId;
  String businessId;
  String productCode; // 8PACKS 16PACKS
  double price;
  String paymentId;
  String receiptNumber;
  DateTime purchaseDate;
  int maxQuantity;
  int usedQuantity;
  

  OrderModel(this.orderId, this.userId, this.businessId,this.productCode, this.price, this.paymentId,
      this.receiptNumber, this.purchaseDate, this.usedQuantity, this.maxQuantity);

  @override
  List<Object> get props =>
      [orderId, userId, businessId, productCode, price, paymentId, receiptNumber, purchaseDate, usedQuantity, maxQuantity];

  factory OrderModel.fromJson(Map<String, dynamic> json) {
    return OrderModel(
        json['orderId'] as String,
        json['userId'] as String,
        json['businessId'] as String,
        json['productCode'] as String,
        json['price'] as double,
        json['paymentId'] as String,
        json['receiptNumber'] as String,
        json['purchaseDate'].toDate() as DateTime,
        json['usedQuantity'] as int,
        json['maxQuantity'] as int,
        );
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['orderId'] = orderId;
    data['userId'] = userId;
    data['businessId'] = businessId;
    data['productCode'] = productCode;
    data['price'] = price;
    data['paymentId'] = paymentId;
    data['receiptNumber'] = receiptNumber;
    data['purchaseDate'] = purchaseDate;
    data['usedQuantity'] = usedQuantity;
    data['maxQuantity'] = maxQuantity;
    return data;
  }
}
