import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedOrder {
  final List<OrderModel> results;

  AutogeneratedOrder({this.results});

  factory AutogeneratedOrder.fromJson(Map<String, dynamic> json) {
    List<OrderModel> temp;
    if (json['results'] != null) {
      temp = <OrderModel>[];
      json['results'].forEach((v) {
        temp.add(OrderModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedOrder(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class OrderModel extends Equatable {
  final int id;
  final String name;

  OrderModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory OrderModel.fromJson(Map<String, dynamic> json) {
    return OrderModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
  
}
