import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedMenuSearch {
  final List<MenuSearchModel> results;

  AutogeneratedMenuSearch({this.results});

  factory AutogeneratedMenuSearch.fromJson(Map<String, dynamic> json) {
    List<MenuSearchModel> temp;
    if (json['results'] != null) {
      temp = <MenuSearchModel>[];
      json['results'].forEach((v) {
        temp.add(MenuSearchModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedMenuSearch(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class MenuSearchModel extends Equatable {
  final int id;
  final String name;

  MenuSearchModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory MenuSearchModel.fromJson(Map<String, dynamic> json) {
    return MenuSearchModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
  
}
