import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedPlaceOrder {
  final List<PlaceOrderModel> results;

  AutogeneratedPlaceOrder({this.results});

  factory AutogeneratedPlaceOrder.fromJson(Map<String, dynamic> json) {
    List<PlaceOrderModel> temp;
    if (json['results'] != null) {
      temp = <PlaceOrderModel>[];
      json['results'].forEach((v) {
        temp.add(PlaceOrderModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedPlaceOrder(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class PlaceOrderModel extends Equatable {
  final int id;
  final String name;

  PlaceOrderModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory PlaceOrderModel.fromJson(Map<String, dynamic> json) {
    return PlaceOrderModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
  
}
