import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedPayment {
  final List<PaymentModel> results;

  AutogeneratedPayment({this.results});

  factory AutogeneratedPayment.fromJson(Map<String, dynamic> json) {
    List<PaymentModel> temp;
    if (json['results'] != null) {
      temp = <PaymentModel>[];
      json['results'].forEach((v) {
        temp.add(PaymentModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedPayment(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class PaymentModel extends Equatable {
  final int id;
  final String name;

  PaymentModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory PaymentModel.fromJson(Map<String, dynamic> json) {
    return PaymentModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
  
}
